config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.urls.conf import include

from member import views as member_views
from post import views as post_views

urlpatterns = [
    path('admin/', admin.site.urls),

    #post
    path('', post_views.PostListView.as_view(), name='main'),
    path('create/', post_views.PostCreateView.as_view(),name='create'),
    path('update/<int:pk>', post_views.PostUpdateView.as_view(), name='update'),

    #like
    path('like/', post_views.toggle_like, name='toggle'),

    #comment
    #path('comment/create',comment_view.as_view(), name='comment_create'),

    #auth
    path('signup/', member_views.SignupView.as_view(), name='signup'),
    path('signup/done/', member_views.SignupView.as_view(), name='signup_done'),
    path('verify/', member_views.verify_email, name='verify_email'),
    #path('signup/done/', TemplateView.as_view(template_name='auth/signup_done.html'), name='signup_done' )
    path('login/', member_views.LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(),name='logout'),

    #search
    path('search/', post_views.search, name='search'),

    #include
    path('comment/', include('post.comment_urls')),
    path('profile/', include('member.urls')),
    path('oauth/', include('member.oauth_urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

member/urls.py
from django.urls import path

from . import views

app_name='profile'
urlpatterns = [

    path('<str:slug>/', views.UserProfileView.as_view(), name='detail'),
    path('<int:pk>/follow/', views.UserFollowingView.as_view(), name='follow'),

]

post/models.py
import re

from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from util.models import TimestampModel

User = get_user_model()


class Post(TimestampModel):
    content = models.TextField('본문')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'[{self.user}] post'

    class Meta:
        verbose_name = '포스트'
        verbose_name_plural = '포스트 목록'


class PostImage(TimestampModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField('이미지', upload_to='post/%Y/%m/%d')

    def __str__(self):
        return f'[{self.post}] image'

    class Meta:
        verbose_name = '이미지'
        verbose_name_plural = '이미지 목록'


class Tag(TimestampModel):
    tag = models.CharField('태그', max_length=100, unique=True)
    post = models.ManyToManyField(Post, related_name='tags')

    def __str__(self):
        return self.tag


class Comment(TimestampModel):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    content = models.CharField('내용', max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.post} | {self.user}'


class Like(TimestampModel):
    post = models.ForeignKey(Post, related_name='likes', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='likes', on_delete=models.CASCADE)

    def __str__(self):
        return f'[like] {self.post} | {self.user}'


@receiver(post_save, sender=Post)
def post_post_save(sender, instance, created, **kwargs):
    hashtags = re.findall(r'#(\w{1,100})(?=\s|$)', instance.content)
    if hashtags:
        tags = [
            Tag.objects.get_or_create(tag=hashtag) for hashtag in hashtags
        ]
        tags = [tag for tag, _ in tags]
        instance.tags.clear()
        instance.tags.add(*tags)

templates/profile/detail.html
{% extends 'base.html' %}
{% load humanize %}
{% block style %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"/>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-10 offset-1 col-lg-6 offset-lg-3">
            <div>
            <span class="p-2 border rounded-circle me-2">
                <i class="fa-solid fa-user" style="width: 16px; padding-left: 3px"></i>
            </span>
                {{ object.nickname }}
                {% if object != request.user %}
                    <form method="post" action="{% url 'profile:follow' object.pk %}" class="d-inline">
                        {% csrf_token %}
                        <button class="btn btn-primary btn-sm ms-3">
                            {% if is_follow %}
                                Unfollow
                            {% else %}
                                Follow
                            {% endif %}
                        </button>
                    </form>
                {% endif %}
            </div>
            <div class="row mt-2">

                <div class="col-4 text-center">{{ object.post_set.count | intcomma }} posts</div>
                <div class="col-4 text-center">
                    <button class="border-0 bg-transparent" data-bs-toggle="modal" data-bs-target="#followers-modal">
                        {{ object.followers.count | intcomma }} followers
                    </button>
                </div>
                <div class="col-4 text-center">
                    <button class="border-0 bg-transparent" data-bs-toggle="modal" data-bs-target="#following-modal">
                        {{ object.following.count | intcomma }} followings
                    </button>
                </div>
            </div>
            <div class="row mt2">
                {% for post in object.post_set.all %}
                    <div class="col-4">
                        <div class="swiper">
                            <div class="border-1 swiper-wrapper">
                                {% for post_image in post.images.all %}
                                    <div class="swiper-slide">
                                        <img src="{{ post_image.image.url }}" alt="" class="img-fluid post-image">
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="swiper-pagination "></div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="followers-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Followers</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <ul>
                        {% for follwer in object.followers.all %}
                            <li>{{ follwer.nickname }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="following-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Following</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <ul>
                        {% for following in object.following.all %}
                            <li>{{ following.nickname }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
    <script>
        const swiper = new Swiper('.swiper', {
            // Optional parameters
            direction: 'horizontal',
            loop: false,

            // If we need pagination
            pagination: {
                el: '.swiper-pagination',
            },
        });</script>
{% endblock %}