config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.urls.conf import include

from member import views as member_views
from post import views as post_views

urlpatterns = [
    path('admin/', admin.site.urls),

    #post
    path('', post_views.PostListView.as_view(), name='main'),
    path('create/', post_views.PostCreateView.as_view(),name='create'),
    path('update/<int:pk>', post_views.PostUpdateView.as_view(), name='update'),

    #like
    path('like/', post_views.toggle_like, name='toggle'),

    #comment
    #path('comment/create',comment_view.as_view(), name='comment_create'),

    #auth
    path('signup/', member_views.SignupView.as_view(), name='signup'),
    path('signup/done/', member_views.SignupView.as_view(), name='signup_done'),
    path('verify/', member_views.verify_email, name='verify_email'),
    #path('signup/done/', TemplateView.as_view(template_name='auth/signup_done.html'), name='signup_done' )
    path('login/', member_views.LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(),name='logout'),

    #search
    path('search/', post_views.search, name='search'),

    #include
    path('comment/', include('post.comment_urls')),
    path('profile/', include('member.urls')),
    path('oauth/', include('member.oauth_urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

member/urls.py
from django.urls import path

from . import views

app_name='profile'
urlpatterns = [

    path('<str:slug>/', views.UserProfileView.as_view(), name='detail'),
    path('<int:pk>/follow/', views.UserFollowingView.as_view(), name='follow'),

]

post/models.py
import re

from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from util.models import TimestampModel

User = get_user_model()


class Post(TimestampModel):
    content = models.TextField('본문')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'[{self.user}] post'

    class Meta:
        verbose_name = '포스트'
        verbose_name_plural = '포스트 목록'


class PostImage(TimestampModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField('이미지', upload_to='post/%Y/%m/%d')

    def __str__(self):
        return f'[{self.post}] image'

    class Meta:
        verbose_name = '이미지'
        verbose_name_plural = '이미지 목록'


class Tag(TimestampModel):
    tag = models.CharField('태그', max_length=100, unique=True)
    post = models.ManyToManyField(Post, related_name='tags')

    def __str__(self):
        return self.tag


class Comment(TimestampModel):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    content = models.CharField('내용', max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.post} | {self.user}'


class Like(TimestampModel):
    post = models.ForeignKey(Post, related_name='likes', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='likes', on_delete=models.CASCADE)

    def __str__(self):
        return f'[like] {self.post} | {self.user}'


@receiver(post_save, sender=Post)
def post_post_save(sender, instance, created, **kwargs):
    hashtags = re.findall(r'#(\w{1,100})(?=\s|$)', instance.content)
    if hashtags:
        tags = [
            Tag.objects.get_or_create(tag=hashtag) for hashtag in hashtags
        ]
        tags = [tag for tag, _ in tags]
        instance.tags.clear()
        instance.tags.add(*tags)

templates/search/search.html
{% extends 'base.html' %}
{% block content %}
    {% include 'include/search_form.html' %}
{% endblock %}

templates/search/search_tag.html
{% extends 'base.html' %}
{% block style %}
{% endblock %}
{% block content %}
    <h1>tag</h1>
    {% include 'include/search_form.html' %}
    <div class="row mt2">
        {% for post in object.post_set.all %}
            <div class="col-4 my-2">
                <div class="swiper">
                    <div class="border-1 swiper-wrapper">
                        {% for post_image in post.images.all %}
                            <div class="swiper-slide">
                                <img src="{{ post_image.image.url }}" alt="" class="img-fluid post-image">
                            </div>
                        {% endfor %}
                    </div>
                    <div class="swiper-pagination "></div>
                </div>
            </div>
        {% endfor %}

    </div>
{% endblock %}
{% block js %}
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
    <script>
        const swiper = new Swiper('.swiper', {
            // Optional parameters
            direction: 'horizontal',
            loop: false,

            // If we need pagination
            pagination: {
                el: '.swiper-pagination',
            },
        });</script>
{% endblock %}

templates/search/search_user.html
{% extends 'base.html' %}
{% block content %}
    {% include 'include/search_form.html' %}
    <div>
        {% for user in object_list %}
            <div class="my-4">
            <a href="{% url 'profile:detail' user.nickname %}" class="text-decoration-none text-black">
                <span class="p-2 border rounded-circle me-2">
                <i class="fa-solid fa-user" style="width: 16px; padding-left: 3px"></i>
            </span>
            {{ user.nickname }}
            </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}